import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { ReactQueryDevtools } from "react-query/devtools";
import NavBar from "@/src/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
          <div className="bg-[#F3F3F3]">
            <NavBar></NavBar>
            <div>{children}</div>
            <ReactQueryDevtools initialIsOpen={false} />
          </div>
      </body>
    </html>
  );
}
